# 3rd feb
# Numpy

In [60]:
import numpy as np   # abs,np we can write ap

In [62]:
np.__version__

'1.26.4'

In [64]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating arrays:

In [67]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [69]:
type(my_list)

list

# we convert list to array

In [72]:
arr=np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [74]:
type(arr)

numpy.ndarray

In [76]:
type(my_list)

list

In [78]:
np.arange(15)  # we pass only argument

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
np.arange(3.0)

array([0., 1., 2.])

In [82]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [86]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
np.arange(20,10)   # 1arg <2nd arg

array([], dtype=int32)

In [90]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [92]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [94]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [96]:
np.arange(30,20)

array([], dtype=int32)

In [98]:
arr=np.arange(-30,20)
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [100]:
np.arange(10,10)

array([], dtype=int32)

In [102]:
np.arange()

TypeError: arange() requires stop to be specified.

In [104]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [106]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [108]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [110]:
np.zeros(3)   #parameter tunning

array([0., 0., 0.])

In [112]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [114]:
np.zeros((2,2),dtype=int )

array([[0, 0],
       [0, 0]])

In [130]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [132]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [118]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [120]:
np.zeros((2,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [122]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [138]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [144]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) 
print(np.zeros(n,dtype=int))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [146]:
np.ones(3)

array([1., 1., 1.])

In [173]:
np.ones(2)

array([1., 1.])

In [148]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [150]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [175]:
range(5)

range(0, 5)

In [177]:
r = range(5)
r

range(0, 5)

In [181]:
for i in r:
    print(i)

0
1
2
3
4


In [183]:
rand(3,2)

NameError: name 'rand' is not defined

In [185]:
rand(3,2)
random.rand(3,2)

NameError: name 'rand' is not defined

In [187]:
np.random.rand(5)  # it gives random values

array([0.22520803, 0.84657966, 0.00705972, 0.77303474, 0.82358406])

In [189]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [191]:
np.random.rand(2,4)

array([[0.08800912, 0.2406321 , 0.14834663, 0.38972398],
       [0.82537868, 0.07961622, 0.98559964, 0.80250473]])

In [193]:
np.random.rand(3,4)

array([[0.28245009, 0.84574344, 0.06480033, 0.73313662],
       [0.83403584, 0.47364221, 0.03211754, 0.61671225],
       [0.96062341, 0.57913552, 0.5806481 , 0.03496362]])

In [195]:
np.random.randint(2,4)

3

In [197]:
np.random.randint(2,20)  #it give value between range

6

In [199]:
np.random.randint(0,1)

0

In [224]:
np.random.randint(10,20,5)

array([13, 19, 12, 19, 11])

# 4th feb

In [227]:
np.random.randint(20,30,10)

array([28, 27, 28, 26, 25, 23, 27, 21, 26, 24])

In [229]:
np.random.randint(10,40,(10,10))

array([[13, 15, 34, 37, 11, 10, 29, 24, 14, 17],
       [10, 29, 25, 13, 20, 13, 16, 29, 15, 37],
       [22, 27, 37, 22, 16, 18, 33, 29, 19, 20],
       [10, 36, 22, 38, 11, 16, 15, 20, 24, 15],
       [39, 14, 15, 24, 11, 22, 39, 22, 12, 13],
       [23, 18, 15, 16, 35, 17, 16, 35, 26, 19],
       [33, 28, 38, 12, 29, 18, 21, 27, 38, 16],
       [15, 31, 31, 23, 20, 12, 35, 32, 27, 36],
       [32, 15, 13, 10, 35, 18, 20, 34, 19, 16],
       [29, 31, 18, 25, 26, 14, 27, 28, 15, 27]])

In [231]:
np.random.randint(1,100,(12,12))

array([[86, 82, 64, 19, 47, 11,  3,  8, 92, 59, 72, 79],
       [71, 93, 91, 30, 91, 89,  7, 63, 46, 82, 63, 63],
       [44, 50, 56, 22, 48, 36, 60, 29, 50, 85, 21, 18],
       [ 7,  7, 96, 32, 76, 11, 79, 64,  6, 48, 87, 49],
       [99, 95, 79, 93, 90, 83, 80,  7, 27, 88, 68, 66],
       [26,  7, 74, 75, 42, 79, 90, 35, 26,  4, 48, 50],
       [52, 27, 95, 76, 85, 32, 86, 86, 87, 97, 48,  9],
       [76,  6, 95, 37, 33, 14, 50, 34, 65, 53, 39, 20],
       [99, 50,  9, 46, 80, 54, 98,  6, 50, 54, 22, 44],
       [ 9, 30, 89, 27, 40,  1, 21, 81, 81,  2, 17,  2],
       [16, 28, 82, 86, 55, 12, 76, 12, 84, 22, 61, 77],
       [19, 76, 87, 79, 51, 73, 37, 26, 78, 72, 64, 33]])

In [233]:
np.arange(1,13).reshape(3,4)    

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [235]:
np.arange(1,13).reshape(5,4)   

ValueError: cannot reshape array of size 12 into shape (5,4)

In [237]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [239]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [293]:
b=np.random.randint(10,20,(5,4))
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [295]:
type(b)

numpy.ndarray

In [297]:
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [299]:
b[:]

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [301]:
b[1:3]

array([[13, 12, 18, 12],
       [12, 16, 19, 11]])

In [303]:
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [305]:
b[1,2]

18

In [307]:
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [309]:
b[1,3]

12

In [311]:
b[1,-1]

12

In [313]:
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [315]:
b[2:3]

array([[12, 16, 19, 11]])

In [317]:
b

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11],
       [15, 12, 14, 10],
       [18, 11, 17, 16]])

In [319]:
b[0:-2]

array([[14, 18, 16, 16],
       [13, 12, 18, 12],
       [12, 16, 19, 11]])

In [337]:
b[0,2]

16

In [339]:
b[-5,-3] 

18

In [341]:
b[-4,2]

18

# operations:

In [344]:
a=np.random.randint(10,20,10)
a

array([14, 16, 10, 14, 11, 11, 12, 19, 11, 16])

In [346]:
id(a)

1733183653328

In [348]:
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [380]:
arr2 = np.random.randint(0,100,(10,10))
arr2

array([[22,  3, 33, 16, 67, 10, 82, 75, 80, 43],
       [12, 17, 78, 59, 42, 43,  7, 11, 50, 79],
       [ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75],
       [77, 20, 82, 15,  0, 76, 94, 33, 77, 40],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [13, 65, 59, 83, 80, 72, 96, 70,  8, 87],
       [84, 55, 67, 23, 69, 35, 12, 52, 62, 84],
       [89, 82, 21, 59,  0, 10, 54, 18,  6, 89]])

In [356]:
arr

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [354]:
arr[:]

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [382]:
arr2

array([[22,  3, 33, 16, 67, 10, 82, 75, 80, 43],
       [12, 17, 78, 59, 42, 43,  7, 11, 50, 79],
       [ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75],
       [77, 20, 82, 15,  0, 76, 94, 33, 77, 40],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [13, 65, 59, 83, 80, 72, 96, 70,  8, 87],
       [84, 55, 67, 23, 69, 35, 12, 52, 62, 84],
       [89, 82, 21, 59,  0, 10, 54, 18,  6, 89]])

In [384]:
arr2[2:]

array([[ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75],
       [77, 20, 82, 15,  0, 76, 94, 33, 77, 40],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [13, 65, 59, 83, 80, 72, 96, 70,  8, 87],
       [84, 55, 67, 23, 69, 35, 12, 52, 62, 84],
       [89, 82, 21, 59,  0, 10, 54, 18,  6, 89]])

In [386]:
arr2[0:5]

array([[22,  3, 33, 16, 67, 10, 82, 75, 80, 43],
       [12, 17, 78, 59, 42, 43,  7, 11, 50, 79],
       [ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75]])

In [388]:
arr2

array([[22,  3, 33, 16, 67, 10, 82, 75, 80, 43],
       [12, 17, 78, 59, 42, 43,  7, 11, 50, 79],
       [ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75],
       [77, 20, 82, 15,  0, 76, 94, 33, 77, 40],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [13, 65, 59, 83, 80, 72, 96, 70,  8, 87],
       [84, 55, 67, 23, 69, 35, 12, 52, 62, 84],
       [89, 82, 21, 59,  0, 10, 54, 18,  6, 89]])

In [390]:
arr2[1,4] 

42

In [392]:
arr2[-5,5] 

76

In [394]:
arr2[-5,-5] 

76

In [396]:
arr2[::-1]

array([[89, 82, 21, 59,  0, 10, 54, 18,  6, 89],
       [84, 55, 67, 23, 69, 35, 12, 52, 62, 84],
       [13, 65, 59, 83, 80, 72, 96, 70,  8, 87],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [77, 20, 82, 15,  0, 76, 94, 33, 77, 40],
       [89, 82, 80, 58, 34, 74,  6, 18, 92, 75],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [ 6, 73, 27,  2, 38, 60, 90, 87, 73,  8],
       [12, 17, 78, 59, 42, 43,  7, 11, 50, 79],
       [22,  3, 33, 16, 67, 10, 82, 75, 80, 43]])

In [398]:
arr2[::-3]

array([[89, 82, 21, 59,  0, 10, 54, 18,  6, 89],
       [54, 39, 91, 64, 84, 64, 26, 88, 78, 33],
       [65,  2, 24, 57, 20, 82, 66, 55, 36, 69],
       [22,  3, 33, 16, 67, 10, 82, 75, 80, 43]])

In [410]:
arr2.max()

96

In [414]:
arr2.min()

0

In [418]:
arr2.mean()

51.16

In [420]:
arr2.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [422]:
from numpy import *
a = array([1,2,3,4,9])
median(a)

3.0

In [428]:
arr= array([0, 1, 2, 3, 4, 5])
arr

array([0, 1, 2, 3, 4, 5])

In [430]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [432]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [434]:
arr.reshape(1,6)  

array([[0, 1, 2, 3, 4, 5]])

In [436]:
arr.reshape(2,4)  

ValueError: cannot reshape array of size 6 into shape (2,4)

In [438]:
arr

array([0, 1, 2, 3, 4, 5])

In [440]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [442]:
arr.reshape(2,3,order='F') 

array([[0, 2, 4],
       [1, 3, 5]])

In [444]:
arr.reshape(2,3,order='A')

array([[0, 1, 2],
       [3, 4, 5]])

In [446]:
arr

array([0, 1, 2, 3, 4, 5])

In [448]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [454]:
arr.reshape(1,3)

ValueError: cannot reshape array of size 6 into shape (1,3)

In [452]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [456]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [458]:
arr.reshape(3,2) 

array([[0, 1],
       [2, 3],
       [4, 5]])

# indexing

In [478]:
mat = np.arange(0,100).reshape(10,10)

In [480]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [482]:
row=4
col=5

In [484]:
col

5

In [486]:
mat[row,col] 

45

In [488]:
mat[4,5] 

45

In [494]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [496]:
mat[row,:] 

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [498]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [500]:
mat[row:] 

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [502]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [504]:
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [506]:
mat[1,4]

14

In [508]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [510]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [514]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [516]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [518]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [520]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [522]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [524]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [529]:
mat[2:6,2:4]

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [531]:
mat[0,1]

1

In [533]:
mat[1,6]

16

In [535]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

# Masking

In [538]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [540]:
id(mat)

1733183652368

In [542]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [544]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [546]:
mat[mat==50] 

array([50])

In [548]:
mat == 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [550]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [552]:
a3 = mat[mat<=50] 
a3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [554]:
a4 = mat[mat==50]
a4

array([50])

In [556]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]


In [558]:
def wish():
    print('good even')
wish()
wish()
wish()

good even
good even
good even


In [560]:
def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

def wish():
    print('good even')
wish()

good even
good even
good even


In [568]:
import random
def generate_otp(length = 4):
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp
otp_length = 4  
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 2325
