In [14]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Numpy

In [20]:
import numpy as np

In [22]:
a=np.arange(6)
a2=a[np.newaxis,:]
a2.shape

(1, 6)

# Array:
  - it is a central data structure of numpy library|numpy package.it is grid of values(ntg but matrix)contain raw data

In [31]:
a=np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [35]:
a=np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:
print(a[0])

[1 2 3 4]


# array are multi dimentional 
  - 1d
  - 2-D
  - nd(used for matrices and vectors(it is single dimension))

In [44]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [48]:
from numpy import*
a=np.array([1,2,3])
a

array([1, 2, 3])

In [50]:
np.zeros(2)
array([0.,0.])

array([0., 0.])

In [52]:
np.ones(2)
array([1.,1.])

array([1., 1.])

In [80]:
np.empty(2)              # gives some space between 1st and last element
array([3.14,42. ])

array([ 3.14, 42.  ])

In [86]:
np.empty(4)
array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [56]:
np.arange(4)
array([0,1,2,3])

array([0, 1, 2, 3])

In [58]:
np.arange(2,9,2)
array([2,4,6,8])

array([2, 4, 6, 8])

In [98]:
np.linspace(0,10,num=5)              # gives space in specified intervals:
array([0.,2.5,5.,7.5,10.])

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [100]:
np.linspace(0,10,num=5)
array([0. ,2.5 ,5. ,7.5 ,10.])

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [108]:
x=np.ones(2,dtype=np.int64)
x

array([1, 1], dtype=int64)

# Sort elements:
   - sort numbers in ascending order

In [136]:
arr=np.array([2,1,5,3,7,4,6,8])
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [138]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# adding
 - concatenate

In [145]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

In [147]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])

In [167]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [197]:
array_example=np.array([[[0,1,2,3],[4,5,6,7],[0,1,2,3],[4,5,6,7],[0,1,2,3],[4,5,6,7]]])
array_example.ndim

3

In [199]:
array_example.size

24

In [211]:
array_example.shape

(1, 6, 4)

# reshape array:
  - new shaping without changing data

In [218]:
a=np.arange(6)
print(a)

[0 1 2 3 4 5]


In [222]:
b=a.reshape(3,2)   # it reshape with 3 rows and 2col 
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [234]:
np.reshape(a, newshape=(1,6),order='c')
array([0,1,2,3,4,5])

array([0, 1, 2, 3, 4, 5])

In [236]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [240]:
a2=a[np.newaxis,:]
a2.shape

(1, 6)

In [246]:
row_vector=a[np.newaxis,:]
row_vector.shape

(1, 6)

In [250]:
col_vector=a[:,np.newaxis]
col_vector.shape

(6, 1)

In [273]:
a=np.array([1,2,3,4,5,6])
a.shape

(6,)

In [281]:
b=np.expand_dims(a,axis=1)    # add an axis at index position 1
b.shape

(6, 1)

In [283]:
c=np.expand_dims(a,axis=0)      # add an axis at index position 0
c.shape

(1, 6)

# indexing and slicing:

In [292]:
data =np.array([1,2,3])  # indexing start from 0 
data[1]

2

In [294]:
data[0:2] # slicing

array([1, 2])

In [296]:
data[1:]

array([2, 3])

In [310]:
data[-2:]   # print values before -2

array([2, 3])

In [312]:
data[:-2]  #print values after -2

array([1])

In [314]:
data[:-1]

array([1, 2])

In [316]:
data[-1:]

array([3])

In [328]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [330]:
print(a[a<5])   #it print number or elemnts

[1 2 3 4]


In [332]:
print([a<5])     # it print whether element  is true or flase the value

[array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])]


In [336]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [353]:
divisible_by_2=a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [346]:
divisible_by_2=a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [355]:
c=a[(a>2) & (a<11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [361]:
five_up=(a>5)|(a==5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [363]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [367]:
b=np.nonzero(a<5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [373]:
b=np.nonzero(a<5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [379]:
list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:    # it iterates the list of cordinates
    print(coord)              # array([0, 0, 0, 0]array([0, 1, 2, 3]

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [381]:
print(a[b])

[1 2 3 4]


In [383]:
not_there=np.nonzero(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# create array for exist data

In [386]:
a=np.array([1,2,3,4,5,6,7,8,9,10])

In [390]:
arr=a[3:8]
arr

array([4, 5, 6, 7, 8])

In [392]:
arr1=a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [394]:
a1=np.array([[1,1],
             [2,2]])
a2=np.array([[3,3],
             [4,5]])

In [398]:
np.vstack((a1,a2))   # vstack means prints vertcally

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 5]])

In [402]:
np.hstack((a1,a2))    # hstack prints horizontally

array([[1, 1, 3, 3],
       [2, 2, 4, 5]])

In [404]:
a1=np.array([[1,1],[2,2]])
a2=np.array([[3,3],[4,5]])

In [406]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 5]])

In [410]:
np.hstack((a1,a2))   # print a1 in c1 and a2 in c2

array([[1, 1, 3, 3],
       [2, 2, 4, 5]])

In [416]:
x=np.arange(1,25).reshape(2,12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [426]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [440]:
np.hsplit(x, (3,4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [444]:
np.hsplit(x, (4,5))

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5],
        [17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [448]:
np.hsplit(x, (6,10))

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]),
 array([[ 7,  8,  9, 10],
        [19, 20, 21, 22]]),
 array([[11, 12],
        [23, 24]])]

In [450]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [472]:
b1 = a[0:]
b1            #slicing

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [468]:
b1[0] = 99       # 0th row all elements = 99
b1

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [470]:
a

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [476]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a1 = a[0,:]
a1  

array([1, 2, 3, 4])

In [478]:
a1[0]=99
a1

array([99,  2,  3,  4])

In [482]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [484]:
a2=a.copy()
a2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [488]:
#data =np.array([1,2])
ones=np.ones(2, dtype=int)
ones
#data+ones

array([1, 1])

In [490]:
data =np.array([1,2])
data

array([1, 2])

In [496]:
data =np.array([1,2])
ones=np.ones(2, dtype=int)       # array([1, 1]) + array([1, 2]) from above codee
data+ones

array([2, 3])

In [498]:
data-ones

array([0, 1])

In [500]:
data*data

array([1, 4])

In [512]:
data/data

array([1., 1.])

In [514]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [522]:
b = np.array([[1, 1], [2, 2]])
b.sum()               # add linearly

6

In [524]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)    # it add over axis position

array([3, 3])

In [528]:
b.sum(axis=1)   # [1,1] =2  ,[2, 2]=4

array([2, 4])

In [530]:
data = np.array([1.0, 2.0])
data*1.6

array([1.6, 3.2])

In [540]:
 data.max()

2.0

In [534]:
 data.min()

1.0

In [550]:
data.sum()

3.0

In [552]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [554]:
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [556]:
a.sum()

4.8595784

In [558]:
a.min()

0.05093587

In [560]:
a.max()

0.82485143

In [562]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [564]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [572]:
data[0,1]   #slicing specify element

2

In [576]:
data[1:3]   # 1st and 2nd row

array([[3, 4],
       [5, 6]])

In [578]:
data[0:2, 0]

array([1, 3])

In [580]:
data[0:3, 0]

array([1, 3, 5])

In [582]:
data.max()

6

In [584]:
data.min()

1

In [586]:
data.sum()

21

In [588]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [590]:
data.max(axis=0)

array([5, 6])

In [592]:
 data.max(axis=1)

array([2, 5, 6])

In [594]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

In [596]:
data+ones

array([[2, 3],
       [4, 5]])

In [602]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [636]:
np.ones((4, 3, 2 ))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [606]:
np.ones(3)

array([1., 1., 1.])

In [608]:
np.zeros(3)

array([0., 0., 0.])

In [610]:
rng=np.random.default_rng()
rng.random(3)

array([0.72588467, 0.45400878, 0.6838141 ])

In [632]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [638]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [640]:
rng.random((3, 2))

array([[0.76703226, 0.24457287],
       [0.54686394, 0.52033203],
       [0.98966185, 0.36774058]])

# generating random numbers:

In [643]:
rng.integers(5, size=(2, 4))

array([[3, 1, 0, 2],
       [0, 4, 4, 0]], dtype=int64)

# How to get unique items and counts

In [646]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [648]:
unique_values=np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [654]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [656]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [660]:
# 2d array:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [662]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [664]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [668]:
unique_rows = np.unique(a_2d, axis=1)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]
