#  Array creation functions:

In [31]:
import numpy as np

In [33]:
a = np.array([1, 2, 3])
print("Array a:", a)

Array a: [1 2 3]


In [37]:
b = np.arange(0, 10, 2)   # range between 0 and 10 with step2
print("Array b:", b)

Array b: [0 2 4 6 8]


In [41]:
c = np.linspace(0, 1, 5)  
print("Array c:", c)

Array c: [0.   0.25 0.5  0.75 1.  ]


In [43]:
d = np.zeros((2, 3))  
print("Array d:\n", d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [45]:
e = np.ones((3, 2))  
print("Array e:\n", e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [47]:
f = np.eye(4) 
print("Identity matrix f:\n", f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# array munipulation:

In [51]:
a1 = np.array([1, 2, 3])
reshaped = np.reshape(a1, (1, 3))  # Reshape an array
print("Reshaped array:", reshaped)

Reshaped array: [[1 2 3]]


In [53]:
f1 = np.array([[1, 2], [3, 4]])
flattened = np.ravel(f1)                   # Flatten array
print("Flattened array:", flattened)

Flattened array: [1 2 3 4]


In [55]:
# Transpose an array
e1 = np.array([[1, 2], [3, 4]])
transposed = np.transpose(e1) 
print("Transposed array:\n", transposed)

Transposed array:
 [[1 3]
 [2 4]]


In [57]:
# stack array
a2 = np.array([1, 2])
b2 = np.array([3, 4])
stacked = np.vstack([a2, b2]) 
print("Stacked arrays:\n", stacked)

Stacked arrays:
 [[1 2]
 [3 4]]


# mathematical :

In [64]:
g = np.array([1, 2, 3, 4])
added = np.add(g, 2) 
print("Added 2 to g:", added)

Added 2 to g: [3 4 5 6]


In [66]:
squared = np.power(g, 2) 
print("Squared g:", squared)

Squared g: [ 1  4  9 16]


In [68]:
sqrt_val = np.sqrt(g)  
print("Square root of g:", sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [70]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [72]:
a2 = np.array([1, 2, 3])
dot_product = np.dot(a2, g)  
print("Dot product of a and g:", dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [74]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [76]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a) 
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


# statistical :

In [79]:
s = np.array([1, 2, 3, 4])
mean = np.mean(s)
print("Mean of s:", mean)

Mean of s: 2.5


In [81]:
std_dev = np.std(s)
print("Standard deviation of s:", std_dev)

Standard deviation of s: 1.118033988749895


In [83]:
minimum = np.min(s)
print("Min of s:", minimum)

Min of s: 1


In [85]:
maximum = np.max(s)
print("Max of s:", maximum)

Max of s: 4


# linear algebra

In [92]:
matrix = np.array([[1, 2], [3, 4]])

In [94]:
determinant = np.linalg.det(matrix)
print("Determinant of matrix:", determinant)

Determinant of matrix: -2.0000000000000004


In [96]:
inverse = np.linalg.inv(matrix)
print("Inverse of matrix:\n", inverse)

Inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


# random sampling

In [99]:
random_vals = np.random.rand(3) 
print("Random values:", random_vals)

Random values: [0.15673241 0.52955739 0.28953954]


In [109]:
np.random.seed(0)
random_vals = np.random.rand(3) 
print("Random values:", random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [111]:
rand_ints = np.random.randint(0, 10, size=5) 
print("Random integers:", rand_ints)

Random integers: [3 7 9 3 5]


In [117]:
np.random.seed(0)
rand_ints = np.random.randint(0, 10, size=5) 
print("Random integers:", rand_ints)

Random integers: [5 0 3 3 7]


# boolean and logical:

In [120]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) 
print("All elements True:", all_true)

All elements True: False


In [122]:
logical_test = np.array([True, False, True])
all_true = np.all(logical_test) 
print("All elements True:", all_true)

All elements True: False


In [124]:
logical_test = np.array([False, False, False])
all_true = np.all(logical_test) 
print("All elements True:", all_true)

All elements True: False


In [126]:
any_true = np.any(logical_test) 
print("Any elements True:", any_true)

Any elements True: False


# set operation:

In [129]:
set_a = np.array([1, 2, 3, 4])
set_b = np.array([3, 4, 5, 6])
intersection = np.intersect1d(set_a, set_b)
print("Intersection of a and b:", intersection)

Intersection of a and b: [3 4]


In [131]:
union = np.union1d(set_a, set_b)
print("Union of a and b:", union)

Union of a and b: [1 2 3 4 5 6]


# array attribute

In [140]:
a = np.array([1, 2, 3])
shape = a.shape  
size = a.size   
dimensions = a.ndim  
dtype = a.dtype  

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)

Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int32


# other fun:

In [143]:
a = np.array([1, 2, 3])
copied_array = np.copy(a)  
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [145]:
array_size_in_bytes = a.nbytes 
print("Size of a in bytes:", array_size_in_bytes)

Size of a in bytes: 12


In [147]:
shared = np.shares_memory(a, copied_array)  
print("Do a and copied_array share memory?", shared)

Do a and copied_array share memory? False
